### ISSUE TITLE
ruby incompatible library

### ISSUE THREAD

**Issue by slslssl** [sjbach/lusty#112]
When using the plugin (ex. :LustyBufferExplorer) the following error is presented
```
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygemsa/specification.rb:17:in `require': incompatible library version - /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18/stringio.bundle (LoadError)
from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/specification.rb:17:in `<top (required)>'
from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:1230:in `require'
from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:1230:in `<module:Gem>'
from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems.rb:116:in `<top (required)>'
from <internal:gem_prelude>:4:in `require' from <internal:gem_prelude>:4:in `<internal:gem_prelude>'
Error detected while processing /Users/slslssl/.vim/bundle/lusty/autoload/lusty               e
xplorer.vim:
line 2231:
LoadError: incompatible library version - /System/Library/Frameworks/Ruby.framew ork/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18/pathname.bundle
Error detected while processing function lustyexplorer#LustyBufferGrepStart:
line    1:
NameError: uninitialized constant LustyE
```

**Comment by slslssl** [comment]
I found the solution; down load from the [Current HEAD](https://github.com/sjbach/lusty) not this vim script clusters  [vim-scripts/LustyExplorer](https://github.com/vim-scripts/LustyExplorer)

**Comment by sjbach** [comment]
Thanks for the report. Do other Ruby-based vim plugins show a similar error for you? "incompatible library version" suggests it might be a configuration issue.

(Aside re: your pre-edit comment: I don't think the https://github.com/vim-scripts scraper is updated anymore, so the version of the plugin it hosts is quite old.)
